/**
 * short-program-migration.test.mjs — 0155/0156 say what they must, and lost nothing on the way.
 *
 * ══ WHY A TEST READS SQL ══
 *
 * These migrations are applied BY HAND in the Supabase SQL editor, so their own `do $$ … $$` self-checks
 * only fire if someone actually runs them. This file asserts the same things at `node --test` time, where
 * they cannot be skipped — the same pattern `notes.test.mjs` established for 0124.
 *
 * The risk being guarded is specific and has happened four times in this schema: rebuilding `save_workout`
 * drops a branch nobody notices until an athlete loses a session. 0156's body was generated by transform
 * rather than typed, and this is the proof that the transform preserved every predecessor's work.
 *
 * Run:  node --test --experimental-strip-types src/domain/program/__tests__/short-program-migration.test.mjs
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const mig = (f) => readFileSync(path.join(here, '../../../../supabase/migrations/', f), 'utf8');

const M155 = mig('0155_program_state_finished.sql');
const M156 = mig('0156_short_program_credit.sql');
const M157 = mig('0157_week_templates.sql');
const M158 = mig('0158_short_program_cap.sql');
const M151 = mig('0151_stair_floors.sql');
const M123 = mig('0123_program_structure_guard.sql');

// ─────────────────────────────────────────────────────────────────────────────
// 0155 — the labels, and NOTHING that would use them
// ─────────────────────────────────────────────────────────────────────────────

test('0155 adds both enum labels', () => {
  assert.match(M155, /alter type program_state\s+add value if not exists 'finished'/);
  assert.match(M155, /alter type flm_event_type add value if not exists 'PROGRAM_COMPLETED'/);
});

test("⚠ 0155 never USES the labels it adds — that is 55P04 and the whole reason it is a separate file", () => {
  // Everything after `commit;` is commented-out verification, so only the live half is checked.
  const live = M155.slice(0, M155.indexOf('commit;'));
  assert.doesNotMatch(live, /'finished'::/, 'a cast to the new label raises inside the adding transaction');
  assert.doesNotMatch(live, /create (or replace )?function/, 'a function body would parse at creation');
  assert.doesNotMatch(live, /create policy/, 'a policy expression would parse at creation');
});

// ─────────────────────────────────────────────────────────────────────────────
// 0156 — the rule, at BOTH doors
// ─────────────────────────────────────────────────────────────────────────────

test('0156 defines the credit predicate and never casts weeks unguarded', () => {
  assert.match(M156, /create or replace function public\.program_earns_credit\(p_structure jsonb\)/);
  assert.match(M156, /jsonb_typeof\(coalesce\(p_structure, '\{\}'::jsonb\)->'weeks'\) = 'number'/);
  // `(j->>'weeks')::int` on {"weeks":"four"} raises, inside the commit that saves the athlete's session.
  assert.doesNotMatch(M156, /\(p_structure->>'weeks'\)::int\b/, 'a bare int cast can raise mid-save');
});

test('⚠ BOTH completion doors are gated — the skip path is the one that gets forgotten', () => {
  const calls = M156.match(/program_earns_credit\(v_prog\.structure\)/g) || [];
  assert.equal(calls.length, 2, 'expected the verdict in save_workout AND skip_program_session');

  const skip = M156.slice(M156.indexOf('create or replace function public.skip_program_session'));
  assert.match(skip, /program_earns_credit/, 'skipping the last session must not graduate a one-week block');
});

test('no unconditional graduation write survives anywhere in 0156', () => {
  assert.doesNotMatch(M156, /set state = 'graduated', ended_at/);
  assert.doesNotMatch(M156, /state = 'graduated', ended_at = now\(\), updated_at = now\(\)\s*\n\s*where/);
});

test('the sealed-state lists all learned the fifth state', () => {
  // start_program's refusal, skip_program_session's refusal, and the structure guard. Miss the guard and
  // a sealed record stays freely restructurable — the one failure here that raises nothing.
  const lists = M156.match(/'graduated', 'finished', 'ended_early'/g) || [];
  assert.ok(lists.length >= 3, `expected >= 3 sealed-state lists, found ${lists.length}`);
  assert.match(M156, /create or replace function public\.programs_guard_structure\(\)/);
});

// ─────────────────────────────────────────────────────────────────────────────
// AND NOTHING WAS LOST IN THE REBUILD
// ─────────────────────────────────────────────────────────────────────────────

test('⚠ 0156 kept every branch 0151 shipped in save_workout', () => {
  const save156 = M156.slice(
    M156.indexOf('create or replace function save_workout('),
    M156.indexOf('create or replace function public.skip_program_session'),
  );
  assert.ok(save156.length > 2000, 'save_workout body not found in 0156');

  for (const marker of [
    'floors',                       // 0151 — a floor is not a mile
    'incline_pct',                  // 0097 — cardio
    'group_kind',                   // 0106 — supersets, deleted once already
    "nullif(v_ex->>'notes', '')",   // 0124 — exercise notes
    'program_slots',                // 0119 — which session this was
    'insert into public.program_sessions',
    'insert into personal_records',
    'update chapters set workout_count',
    "evaluate_honors('live_session')",
    'PROGRAM_GRADUATED',
    'p_program_week',
  ]) {
    assert.ok(M151.includes(marker), `precondition: 0151 should contain "${marker}"`);
    assert.ok(save156.includes(marker), `0156 DROPPED "${marker}" from save_workout — regenerate it from 0151`);
  }
});

test('0156 kept every branch 0123 shipped in skip_program_session', () => {
  const skip156 = M156.slice(M156.indexOf('create or replace function public.skip_program_session'));
  for (const marker of ['program_slots', 'program_total_sessions', 'on conflict', "evaluate_honors('live_session')"]) {
    assert.ok(M123.includes(marker), `precondition: 0123 should contain "${marker}"`);
    assert.ok(skip156.includes(marker), `0156 DROPPED "${marker}" from skip_program_session`);
  }
});

test('0156 replaces rather than drops, so every grant survives', () => {
  assert.doesNotMatch(M156, /drop function/i);
  assert.match(M156, /create or replace function save_workout/);
  assert.match(M156, /create or replace function public\.skip_program_session/);
});

test('the short path never emits the graduation ceremony payload', () => {
  // `v_grad` IS the M-4 trigger. If it survives for a short block, the ceremony fires for a completion
  // the ladder does not count (M4-A1-D1).
  assert.match(M156, /if \(not v_credit\) then/);
  assert.match(M156, /v_grad := null;/);
  assert.match(M156, /'completed', v_fin/, 'W-17 needs the quiet twin to render its inline state');
  assert.doesNotMatch(M156, /v_fin\s*:=\s*v_grad;/, 'the short payload must not keep a graduated_at key');
});

/*
 * ⚠ THIS ONE CAUGHT NOTHING AND SHOULD HAVE — added after the fact, 2026-08-13.
 *
 * 0156 shipped to the PO with `as $` where `as $$` belonged, and Postgres refused the whole file with
 * `42601: syntax error at or near "$"`. Every other gate was green: it is a comment-free, type-free,
 * test-free region of a .sql file that nothing in this repo parses.
 *
 * The cause is worth naming because it will happen again to anyone generating SQL from JS:
 * `String.prototype.replace(search, replacement)` treats `$$` IN THE REPLACEMENT STRING as an escape
 * for one literal `$`. Passing a SQL body as that replacement silently halves every `$$` fence in it.
 * `save_workout` survived only because it is fenced with `$fn$`, which has no doubled dollar.
 * (The fix at the source is `replace(token, () => body)` — a replacement function gets no such handling.)
 */
test('⚠ every dollar-quote fence is balanced — a halved `$$` is a file Postgres will not parse', () => {
  for (const [name, src] of [['0155', M155], ['0156', M156], ['0157', M157], ['0158', M158]]) {
    // A `$` that is neither part of `$$` nor part of a `$tag$` fence is always a broken fence here.
    const lone = [...src.matchAll(/(^|[^$A-Za-z_])\$([^$A-Za-z_]|$)/g)];
    assert.equal(lone.length, 0, `${name}: ${lone.length} lone $ — a dollar-quote fence was halved`);

    const tags = {};
    for (const m of src.matchAll(/\$[A-Za-z_]*\$/g)) tags[m[0]] = (tags[m[0]] ?? 0) + 1;
    for (const [tag, n] of Object.entries(tags)) {
      assert.equal(n % 2, 0, `${name}: ${tag} appears ${n} times — fences come in pairs`);
    }
  }
});

test('the ordering hazard is stated where someone applying these will read it', () => {
  assert.match(M155, /RUN 0155 FIRST|its own migration/i);
  assert.match(M156, /RUN 0155 FIRST/);
  assert.match(M156, /55P04/);
});
