/**
 * ExerciseRelationship — schema for the Forge Legacy exercise relationship graph.
 *
 * This is the normalized, directional edge model that BACKS the three
 * relationship arrays defined in Exercise-Library-Architecture-v1.0 (EL-D12):
 *
 *   alternativeExerciseIds  ← { Substitute, Equipment Alternative, Variation }
 *   regressionExerciseIds   ← { Regression }
 *   progressionExerciseIds  ← { Progression }
 *
 * The graph is generated by ./engine.mjs + ./generate.mjs from the canonical
 * catalog in ./source/. Every edge stays `editorialStatus: "Auto-Generated"`
 * until a human editor reviews it (Exercise-002 §7: relationship arrays are
 * authored/curated by the Forge content team; this graph is the first pass).
 *
 * See README.md for the full scoring formula and integration notes.
 */

/**
 * Canonical MovementPattern taxonomy for the exercise catalog (data layer).
 *
 * This is the authoritative set of `movementPattern` values every FORGE exercise
 * must use. `Shoulder Isolation` and `Neck Isolation` were added in the July 2026
 * source-correction pass (parallel to the existing `Hip Isolation` / `Calf / Ankle`
 * isolation patterns). `Other` is the explicit non-discriminating catch-all —
 * exercises with `Other` never receive relationships. See
 * Exercise-Library-Architecture-v1.0 §4 (Amendment R1-6) for the governance note.
 */
export type MovementPattern =
  | 'Squat / Knee Dominant'
  | 'Hinge / Hip Dominant'
  | 'Horizontal Push'
  | 'Vertical Push'
  | 'Horizontal Pull'
  | 'Vertical Pull'
  | 'Elbow Flexion'
  | 'Elbow Extension'
  | 'Core'
  | 'Carry'
  | 'Cardio / Locomotion'
  | 'Power / Plyometric'
  | 'Mobility'
  | 'Calf / Ankle'
  | 'Hip Isolation'
  | 'Shoulder Isolation'
  | 'Neck Isolation'
  | 'Other';

export const MOVEMENT_PATTERNS: readonly MovementPattern[] = [
  'Squat / Knee Dominant',
  'Hinge / Hip Dominant',
  'Horizontal Push',
  'Vertical Push',
  'Horizontal Pull',
  'Vertical Pull',
  'Elbow Flexion',
  'Elbow Extension',
  'Core',
  'Carry',
  'Cardio / Locomotion',
  'Power / Plyometric',
  'Mobility',
  'Calf / Ankle',
  'Hip Isolation',
  'Shoulder Isolation',
  'Neck Isolation',
  'Other',
];

/** The five — and only five — relationship types. */
export type RelationshipType =
  | 'Substitute'
  | 'Equipment Alternative'
  | 'Regression'
  | 'Progression'
  | 'Variation';

export const RELATIONSHIP_TYPES: readonly RelationshipType[] = [
  'Substitute',
  'Equipment Alternative',
  'Regression',
  'Progression',
  'Variation',
];

export type EditorialStatus = 'Auto-Generated' | 'Editor-Approved' | 'Editor-Edited';

/**
 * A single directional relationship edge: sourceExerciseId → targetExerciseId.
 * Directionality is intentional: A → B does NOT imply B → A. The inverse of a
 * Progression is a Regression and vice-versa; alternative-family types tend to
 * be mutual but are computed independently per direction.
 */
export interface ExerciseRelationship {
  /** Deterministic id: `${sourceExerciseId}__${targetExerciseId}`. */
  id: string;
  sourceExerciseId: string;
  targetExerciseId: string;
  type: RelationshipType;
  /** 1-based position within the source exercise's list (score desc, id asc tiebreak). */
  rank: number;
  /** 0–100, one decimal. Movement pattern carries the largest weight. */
  compatibilityScore: number;
  /** The movement pattern shared by source and target (the pattern being preserved). */
  movementPattern: string;
  /** TRUE only when both exercises share the same real (non-"Other") movement pattern. */
  preservesPattern: boolean;
  /** TRUE only when source & target share ≥1 real anatomical primary muscle (system buckets excluded). */
  samePrimaryMuscle: boolean;
  /** The real anatomical primary muscles shared by both (may be empty). */
  sharedPrimaryMuscleIds: string[];
  /** TRUE when source.equipmentId !== target.equipmentId. */
  equipmentChange: boolean;
  /** Situational labels, derived AFTER the type is chosen. Never medical claims. */
  swapContexts: string[];
  /** One concise human-readable sentence describing the actual relationship. */
  reason: string;
  editorialStatus: EditorialStatus;
}

/** Muscle ids that are descriptors, not anatomical muscles — excluded from all similarity scoring. */
export const SYSTEM_MUSCLE_IDS: readonly string[] = [
  'full_body',
  'cardiovascular',
  'mobility',
  'grip',
  'balance',
];

/** Movement-pattern values that are non-discriminating (never a basis for a relationship). */
export const NON_DISCRIMINATING_PATTERNS: readonly string[] = ['Other'];

/** Projection of the edge graph onto the locked EL-D12 relationship arrays for one exercise. */
export interface ExerciseRelationshipArrays {
  exerciseId: string;
  alternativeExerciseIds: string[];
  regressionExerciseIds: string[];
  progressionExerciseIds: string[];
}
