from usda import foods, nut

# key: (fdc_id, display name, allergens, diet class, US measure)
#   diet class: meat | fish | shellfish | animal (dairy/egg/honey) | plant
#   US measure (grams per unit from USDA food_portion.csv):
#     ('oz',)  ·  ('cup', g)  ·  ('tsp', g)  ·  ('each', g, one, many)
I = {
 'greek_yogurt':(170894,'Greek yogurt, plain nonfat',['dairy'],'animal',('each',170,'container','containers')),
 'granola':(171646,'Granola',['gluten','tree_nuts'],'plant',('cup',122)),
 'blueberries':(171711,'Blueberries',[],'plant',('cup',148)),
 'strawberries':(167762,'Strawberries, halved',[],'plant',('cup',152)),
 'honey':(169640,'Honey',[],'animal',('tsp',7)),
 'sirloin':(174763,'Sirloin steak, trimmed',[],'meat',('oz',)),
 'egg':(171287,'Eggs',['eggs'],'animal',('each',50,'large egg','large eggs')),
 'potato':(170026,'Potatoes',[],'plant',('each',213,'medium potato','medium potatoes')),
 'red_pepper':(170108,'Red bell pepper',[],'plant',('each',119,'pepper','peppers')),
 'olive_oil':(171413,'Olive oil',[],'plant',('tsp',4.5)),
 'oats':(173904,'Rolled oats',['gluten'],'plant',('cup',81)),
 'peanut_butter':(172470,'Peanut butter, smooth',['peanuts'],'plant',('tsp',5.33)),
 'banana':(173944,'Banana',[],'plant',('each',118,'medium banana','medium bananas')),
 'rice_milk':(171942,'Rice milk, unsweetened',[],'plant',('cup',240)),
 'smoked_salmon':(173687,'Smoked salmon',['fish'],'fish',('oz',)),
 'bagel':(174899,'Plain bagel',['gluten','sesame'],'plant',('each',105,'bagel','bagels')),
 'cream_cheese':(173418,'Cream cheese',['dairy'],'animal',('tsp',4.83)),
 'capers':(172238,'Capers, drained',[],'plant',('tsp',2.87)),
 'tofu':(172475,'Firm tofu',['soy'],'plant',('oz',)),
 'black_beans':(175238,'Black beans, canned, drained',[],'plant',('cup',240)),
 'spinach':(168462,'Baby spinach',[],'plant',('cup',30)),
 'flour_tortilla':(175037,'Flour tortilla (10-inch)',['gluten'],'plant',('each',72,'tortilla','tortillas')),
 'flour':(168894,'All-purpose flour',['gluten'],'plant',('cup',125)),
 'whey':(173180,'Whey protein powder',['dairy'],'animal',('cup',97)),
 'milk':(171267,'Milk, 2%',['dairy'],'animal',('cup',244)),
 'turkey_sausage':(174617,'Turkey sausage',[],'meat',('oz',)),
 'cheddar':(173414,'Cheddar, shredded',['dairy'],'animal',('cup',113)),
 'canned_tomatoes':(170051,'Canned tomatoes',[],'plant',('cup',240)),
 'feta':(173420,'Feta, crumbled',['dairy'],'animal',('cup',150)),
 'wholewheat_bread':(172688,'Whole-wheat bread',['gluten'],'plant',('each',32,'slice','slices')),
 'cottage_cheese':(172182,'Cottage cheese, 2%',['dairy'],'animal',('cup',226)),
 'almonds':(170567,'Almonds',['tree_nuts'],'plant',('cup',143)),
 'peach':(169928,'Peach',[],'plant',('each',150,'medium peach','medium peaches')),
 'chia':(170554,'Chia seeds',[],'plant',('oz',)),
 'coconut_milk':(170173,'Coconut milk, canned',[],'plant',('cup',226)),
 'mango':(169910,'Mango, diced',[],'plant',('cup',165)),
 'chicken_breast':(171077,'Chicken breast, boneless skinless',[],'meat',('oz',)),
 'white_rice':(168877,'Long-grain white rice, dry',[],'plant',('cup',185)),
 'tahini':(170189,'Tahini',['sesame'],'plant',('tsp',5)),
 'cucumber':(168409,'Cucumber',[],'plant',('cup',104)),
 'tuna':(173709,'Tuna in water, drained',['fish'],'fish',('oz',)),
 'white_beans':(175204,'White beans, canned, drained',[],'plant',('cup',262)),
 'arugula':(169387,'Rocket (arugula)',[],'plant',('cup',20)),
 'lemon':(167747,'Lemon juice',[],'plant',('tsp',5.08)),
 'deli_turkey':(172941,'Sliced turkey breast',[],'meat',('each',16,'slice','slices')),
 'avocado':(171706,'Avocado',[],'plant',('each',136,'avocado','avocados')),
 'lentils':(172420,'Brown or green lentils, dry',[],'plant',('cup',192)),
 'carrot':(170393,'Carrot',[],'plant',('each',61,'medium carrot','medium carrots')),
 'butternut':(169295,'Butternut squash, cubed',[],'plant',('cup',140)),
 'onion':(170000,'Onion',[],'plant',('each',150,'large onion','large onions')),
 'veg_broth':(171583,'Vegetable broth',[],'plant',('cup',221)),
 'chickpeas':(173800,'Chickpeas, canned, drained',[],'plant',('each',253,'can, drained','cans, drained')),
 'quinoa':(168874,'Quinoa, dry',[],'plant',('cup',170)),
 'kale':(168421,'Kale, chopped',[],'plant',('cup',21)),
 'halloumi':(170846,'Halloumi',['dairy'],'animal',('oz',)),
 'bulgur':(170688,'Bulgur, dry',['gluten'],'plant',('cup',140)),
 'mint':(173475,'Fresh mint',[],'plant',('tsp',1.9)),
 'shrimp':(175179,'Raw prawns, peeled',['shellfish'],'shellfish',('oz',)),
 'wheat_noodles':(168908,'Wheat noodles, dry',['gluten'],'plant',('oz',)),
 'soy_sauce':(174277,'Soy sauce',['soy','gluten'],'plant',('tsp',5.3)),
 'bok_choy':(170390,'Bok choy',[],'plant',('cup',70)),
 'ground_beef':(174030,'Lean ground beef (90%)',[],'meat',('oz',)),
 'edamame':(168411,'Edamame, shelled',['soy'],'plant',('cup',155)),
 'pita':(174915,'Pita (6½-inch)',['gluten'],'plant',('each',60,'pita','pitas')),
 'yogurt':(171284,'Plain yogurt',['dairy'],'animal',('cup',245)),
 'salmon':(175167,'Salmon fillet',['fish'],'fish',('oz',)),
 'sweet_potato':(168482,'Sweet potato',[],'plant',('each',130,'sweet potato','sweet potatoes')),
 'broccoli':(170379,'Broccoli florets',[],'plant',('cup',91)),
 'kidney_beans':(174285,'Kidney beans, canned, drained',[],'plant',('each',266,'can, drained','cans, drained')),
 'chicken_thigh':(173627,'Chicken thighs, boneless skinless',[],'meat',('oz',)),
 'ground_turkey':(171505,'Ground turkey',[],'meat',('oz',)),
 'mushrooms':(169251,'Mushrooms, sliced',[],'plant',('cup',70)),
 'green_beans':(169961,'Green beans',[],'plant',('cup',100)),
 'butter':(173410,'Butter',['dairy'],'animal',('tsp',4.73)),
 'cod':(171955,'Cod fillet',['fish'],'fish',('oz',)),
 'parmesan':(171247,'Parmesan, grated',['dairy'],'animal',('tsp',1.67)),
 'pasta':(169736,'Orzo or pasta, dry',['gluten'],'plant',('oz',)),
 'spaghetti':(169736,'Spaghetti, dry',['gluten'],'plant',('oz',)),
 'salsa':(174524,'Salsa',[],'plant',('tsp',6)),
 'teriyaki':(171167,'Teriyaki sauce',['soy','gluten'],'plant',('tsp',6)),
 'sesame_seeds':(170150,'Sesame seeds',['sesame'],'plant',('tsp',3)),
 'pork':(168249,'Pork tenderloin',[],'meat',('oz',)),
 'cabbage':(169975,'Cabbage, shredded',[],'plant',('cup',70)),
 'vinegar':(173469,'Cider vinegar',[],'plant',('tsp',5)),
 'barley':(170284,'Pearl barley, dry',['gluten'],'plant',('cup',200)),
 'sour_cream':(171257,'Sour cream',['dairy'],'animal',('tsp',4)),
 'apple':(171688,'Apple',[],'plant',('each',182,'medium apple','medium apples')),
 'hummus':(174289,'Hummus',['sesame'],'plant',('tsp',5)),
 'raisins':(168165,'Raisins',[],'plant',('cup',145)),
 'peanuts':(173806,'Dry-roasted peanuts',['peanuts'],'plant',('cup',146)),
 'boiled_egg':(173424,'Eggs, hard-boiled',['eggs'],'animal',('each',50,'large egg','large eggs')),
 'grapes':(174683,'Grapes',[],'plant',('cup',151)),
 'rice_cakes':(170250,'Brown rice cakes',[],'plant',('each',9,'rice cake','rice cakes')),
 'beef_jerky':(167536,'Beef jerky',['soy','gluten'],'meat',('oz',)),
 'orange':(169097,'Orange',[],'plant',('each',131,'orange','oranges')),
 'tomato':(170457,'Tomatoes, chopped',[],'plant',('cup',180)),
 'garlic':(169230,'Garlic',[],'plant',('each',3,'clove','cloves')),
 'ginger':(169231,'Fresh ginger, grated',[],'plant',('tsp',2)),
 'chili_powder':(171319,'Chilli powder',[],'plant',('tsp',2.7)),
 'cumin':(170923,'Cumin',[],'plant',('tsp',2.1)),
 'paprika':(171329,'Smoked paprika',[],'plant',('tsp',2.3)),
 'curry_powder':(170924,'Curry powder',[],'plant',('tsp',2)),
 'oregano':(171328,'Dried oregano',[],'plant',('tsp',1)),
 'cinnamon':(171320,'Ground cinnamon',[],'plant',('tsp',2.6)),
 'salt':(173468,'Salt',[],'plant',('tsp',6)),
 'pepper':(170931,'Black pepper',[],'plant',('tsp',2.3)),
}

S = lambda t, x, m=None: (t, x, m)
LEFTOVERS = S('Store the leftovers', 'Cool within 2 hours and refrigerate in a sealed container. Reheat until piping hot all the way through.')

# id, slot, name, minutes, batch, equipment, [(ingredient, grams per serving)], steps
R = [
 ('b01','breakfast','Greek yogurt bowl with granola and berries',5,False,[],
  [('greek_yogurt',300),('granola',60),('blueberries',75),('strawberries',75),('honey',15)],
  [S('Build the bowl','Spoon the yogurt into a bowl.'),
   S('Top it','Scatter over the granola and berries, then drizzle with the honey.')]),
 ('b02','breakfast','Steak and egg hash',25,False,[],
  [('sirloin',130),('egg',100),('potato',200),('red_pepper',75),('olive_oil',10),('salt',1),('pepper',0.5)],
  [S('Crisp the potatoes','Dice the potatoes small. Heat the oil in a large pan over medium-high heat and cook the potatoes, turning now and then, until golden and tender.',12),
   S('Add the pepper','Stir in the diced pepper and cook until it softens.',3),
   S('Cook the steak','Push everything to the side. Season the steak with salt and pepper and sear it in the pan, 2–3 minutes a side for medium. Rest it, then slice.',6),
   S('Fry the eggs','Crack the eggs into the pan and cook until the whites are fully set.',3),
   S('Serve','Pile the hash on a plate with the sliced steak and eggs on top.')]),
 ('b03','breakfast','Peanut butter overnight oats',5,False,[],
  [('oats',80),('peanut_butter',32),('banana',100),('rice_milk',240),('cinnamon',1)],
  [S('Mix','Stir the oats, rice milk, peanut butter and cinnamon together in a jar or container.'),
   S('Chill overnight','Cover and refrigerate for at least 6 hours.'),
   S('Serve','Slice the banana over the top. Eat cold.')]),
 ('b04','breakfast','Smoked salmon bagel',10,False,[],
  [('bagel',105),('smoked_salmon',85),('cream_cheese',40),('capers',10),('lemon',5),('pepper',0.3)],
  [S('Toast','Split and toast the bagel.',3),
   S('Spread','Spread both halves with the cream cheese.'),
   S('Top and serve','Lay over the smoked salmon, scatter the capers, add a squeeze of lemon and a grind of pepper.')]),
 ('b05','breakfast','Tofu scramble with black beans',15,False,[],
  [('tofu',200),('black_beans',120),('spinach',60),('flour_tortilla',45),('olive_oil',7),('cumin',1),('paprika',1),('salt',1)],
  [S('Crumble the tofu','Pat the tofu dry and crumble it with your hands.'),
   S('Cook','Heat the oil in a pan over medium heat. Add the tofu, cumin, paprika and salt and cook, stirring, until lightly golden.',6),
   S('Add beans and spinach','Stir in the beans and spinach and cook until the beans are hot and the spinach wilts.',3),
   S('Serve','Warm the tortilla in a dry pan and serve with the scramble.',1)]),
 ('b06','breakfast','Protein pancakes with banana',20,False,[],
  [('flour',50),('egg',100),('whey',30),('milk',120),('banana',100),('honey',10),('butter',3)],
  [S('Make the batter','Whisk the flour, protein powder, eggs and milk until smooth. Rest for 2 minutes.',3),
   S('Cook the pancakes','Melt a little butter in a non-stick pan over medium heat. Pour in small rounds of batter and cook until bubbles form, then flip and cook until set.',10),
   S('Serve','Stack the pancakes, top with sliced banana and drizzle with honey.')]),
 ('b07','breakfast','Turkey sausage breakfast burrito',20,False,[],
  [('turkey_sausage',100),('egg',100),('cheddar',28),('flour_tortilla',70),('salsa',30)],
  [S('Cook the sausage','Remove the sausage from its casing and cook in a pan over medium-high heat, breaking it up, until browned and cooked through (165°F / 74°C).',8),
   S('Scramble the eggs','Lower the heat, add the beaten eggs and stir gently until just set.',3),
   S('Fill and roll','Warm the tortilla. Fill with the sausage and eggs, top with the cheese and salsa, and roll up tightly.',2),
   S('Toast','Toast the burrito seam-side down in the pan until golden.',2)]),
 ('b08','breakfast','Shakshuka with feta and toast',25,False,[],
  [('egg',150),('canned_tomatoes',250),('feta',40),('wholewheat_bread',60),('olive_oil',10),('onion',60),('garlic',3),('cumin',1),('paprika',1),('salt',1)],
  [S('Soften the onion','Heat the oil in a small pan over medium heat. Cook the diced onion until soft.',5),
   S('Build the sauce','Add the garlic, cumin and paprika for 30 seconds, then the tomatoes and salt. Simmer until slightly thickened.',8),
   S('Cook the eggs','Make small wells and crack in the eggs. Cover and cook until the whites are fully set.',7),
   S('Serve','Crumble over the feta and serve with toast.')]),
 ('b09','breakfast','Cottage cheese and almond toast',5,False,[],
  [('cottage_cheese',225),('almonds',20),('wholewheat_bread',60),('peach',150),('honey',5)],
  [S('Toast','Toast the bread.',3),
   S('Top','Spread the cottage cheese over the toast.'),
   S('Finish','Top with the sliced peach and chopped almonds, and drizzle with the honey.')]),
 ('b10','breakfast','Chia pudding with mango',5,False,[],
  [('chia',40),('coconut_milk',120),('rice_milk',120),('mango',150)],
  [S('Mix','Stir the chia seeds, coconut milk and rice milk together. Wait 5 minutes and stir again to break up clumps.'),
   S('Chill','Cover and refrigerate for at least 4 hours, or overnight.'),
   S('Serve','Top with the diced mango.')]),

 ('l01','lunch','Chicken shawarma rice bowl',30,False,[],
  [('chicken_breast',220),('white_rice',85),('tahini',20),('cucumber',80),('tomato',80),('olive_oil',10),('lemon',10),('cumin',1),('paprika',1),('garlic',3),('salt',1)],
  [S('Cook the rice','Rinse the rice and simmer, covered, in twice its volume of water until tender. Rest for 5 minutes.',18),
   S('Season the chicken','Slice the chicken into strips and toss with the oil, cumin, paprika, grated garlic and salt.'),
   S('Cook the chicken','Cook in a hot pan, turning, until browned and cooked through (165°F / 74°C).',8),
   S('Make the sauce','Stir the tahini with the lemon juice and a splash of water until pourable.'),
   S('Build the bowl','Serve the chicken over the rice with the diced cucumber and tomato, and drizzle with the sauce.')]),
 ('l02','lunch','Tuna, white bean and rocket salad',10,False,[],
  [('tuna',140),('white_beans',200),('arugula',40),('lemon',15),('olive_oil',20),('tomato',80),('salt',0.5),('pepper',0.3)],
  [S('Make the dressing','Whisk the oil, lemon juice, salt and pepper in a bowl.'),
   S('Toss','Add the beans, tomatoes and tuna and toss gently.'),
   S('Serve','Fold in the rocket just before eating.')]),
 ('l03','lunch','Turkey and avocado wrap',10,False,[],
  [('deli_turkey',120),('avocado',75),('flour_tortilla',90),('cheddar',28),('spinach',30),('lemon',3)],
  [S('Mash the avocado','Mash the avocado with the lemon juice.'),
   S('Fill','Spread the avocado over the tortilla, then layer the turkey, cheese and spinach.'),
   S('Roll','Roll up tightly and cut in half.')]),
 ('l04','lunch','Lentil and roasted vegetable soup',40,True,['Sheet pan'],
  [('lentils',100),('carrot',100),('butternut',150),('onion',80),('olive_oil',15),('veg_broth',350),('wholewheat_bread',60),('garlic',3),('cumin',1),('salt',1)],
  [S('Roast the vegetables','Heat the oven to 425°F (220°C). Toss the diced carrot, squash and onion with the oil and salt, and roast on a sheet pan until tender and browned.',25),
   S('Cook the lentils','Meanwhile rinse the lentils and simmer them in the broth with the garlic and cumin until soft.',25),
   S('Combine','Stir the roasted vegetables into the lentils. Blend a little of the soup if you like it thicker.',3),
   S('Serve','Season to taste and serve with the bread.'),
   LEFTOVERS]),
 ('l05','lunch','Chickpea and quinoa power bowl',20,False,[],
  [('chickpeas',150),('quinoa',65),('kale',60),('tahini',25),('lemon',15),('avocado',50),('salt',0.5)],
  [S('Cook the quinoa','Rinse the quinoa and simmer in twice its volume of water until the water is absorbed.',15),
   S('Massage the kale','Rub the kale with a pinch of salt and half the lemon juice until it softens.',2),
   S('Make the dressing','Stir the tahini with the rest of the lemon juice and a splash of water.'),
   S('Build the bowl','Top the quinoa with the kale, chickpeas and sliced avocado, and drizzle with the dressing.')]),
 ('l06','lunch','Halloumi grain salad',20,False,[],
  [('halloumi',90),('bulgur',70),('tomato',100),('cucumber',80),('mint',5),('olive_oil',15),('lemon',15)],
  [S('Soak the bulgur','Cover the bulgur with boiling water and leave, covered, until tender. Drain well.',12),
   S('Grill the halloumi','Slice the halloumi and cook in a dry pan until golden on both sides.',4),
   S('Toss','Mix the bulgur with the diced tomato and cucumber, chopped mint, oil and lemon juice.'),
   S('Serve','Top with the halloumi.')]),
 ('l07','lunch','Prawn noodle stir-fry',20,False,[],
  [('shrimp',170),('wheat_noodles',95),('soy_sauce',18),('bok_choy',120),('olive_oil',15),('sesame_seeds',6),('garlic',3),('ginger',4)],
  [S('Cook the noodles','Boil the noodles until just tender. Drain and rinse under cold water.',4),
   S('Cook the prawns','Heat the oil in a wok or large pan over high heat. Stir-fry the prawns until pink and opaque all the way through.',3),
   S('Add the greens','Add the garlic, ginger and bok choy and stir-fry until the bok choy wilts.',2),
   S('Toss and serve','Add the noodles and soy sauce and toss until hot. Scatter with sesame seeds.',2)]),
 ('l08','lunch','Beef burrito bowl',25,False,[],
  [('ground_beef',185),('white_rice',70),('black_beans',120),('cheddar',28),('salsa',60),('chili_powder',2),('cumin',1),('salt',1)],
  [S('Cook the rice','Rinse the rice and simmer, covered, in twice its volume of water until tender.',18),
   S('Brown the beef','Cook the beef in a pan over medium-high heat, breaking it up, until browned with no pink left (160°F / 71°C).',7),
   S('Season','Stir in the chilli powder, cumin, salt and a splash of water, and simmer until it coats the meat.',2),
   S('Warm the beans','Warm the beans in a small pan or the microwave.',2),
   S('Build the bowl','Layer the rice, beans and beef. Top with the cheese and salsa.')]),
 ('l09','lunch','Egg fried rice with edamame',15,False,[],
  [('white_rice',100),('egg',100),('edamame',100),('soy_sauce',15),('olive_oil',15),('garlic',3)],
  [S('Use cold rice','Cook the rice ahead and chill it. Fresh rice turns mushy when fried.'),
   S('Scramble the eggs','Heat half the oil in a wok over high heat. Scramble the eggs until just set and set them aside.',2),
   S('Fry the rice','Add the rest of the oil, the garlic and the edamame, then the rice. Stir-fry until hot and starting to crisp.',5),
   S('Finish','Return the eggs, add the soy sauce and toss to combine.',1)]),
 ('l10','lunch','Mediterranean chicken pita',15,False,[],
  [('chicken_breast',200),('pita',90),('yogurt',60),('cucumber',50),('tomato',80),('olive_oil',10),('oregano',1),('garlic',3),('lemon',5),('salt',1)],
  [S('Cook the chicken','Slice the chicken thinly, toss with the oil, oregano and salt, and cook in a hot pan until cooked through (165°F / 74°C).',8),
   S('Make the tzatziki','Grate the cucumber, squeeze out the water, and stir into the yogurt with the grated garlic and lemon juice.',3),
   S('Fill','Warm the pita. Fill with the chicken, tomato and tzatziki.',1)]),

 ('d01','dinner','Salmon, sweet potato and greens',30,False,['Sheet pan'],
  [('salmon',180),('sweet_potato',250),('broccoli',150),('olive_oil',10),('lemon',10),('salt',1),('pepper',0.3)],
  [S('Roast the sweet potato','Heat the oven to 425°F (220°C). Cut the sweet potato into wedges, toss with half the oil and salt, and roast on a sheet pan.',15),
   S('Add the salmon and broccoli','Add the broccoli to the pan with the rest of the oil. Season the salmon and lay it on the pan.'),
   S('Roast','Roast until the salmon flakes easily and reaches 145°F (63°C).',12),
   S('Serve','Squeeze over the lemon.')]),
 ('d02','dinner','Beef chilli with rice',45,True,[],
  [('ground_beef',160),('white_rice',85),('kidney_beans',120),('canned_tomatoes',200),('onion',60),('red_pepper',60),('olive_oil',8),('garlic',6),('chili_powder',4),('cumin',2),('salt',1)],
  [S('Soften the vegetables','Heat the oil in a large pot over medium-high heat. Add the diced onion and pepper and cook until soft.',5),
   S('Brown the beef','Add the beef. Break it up and cook until no pink remains.',7),
   S('Toast the spices','Stir in the garlic, chilli powder and cumin and cook until fragrant.',1),
   S('Simmer','Add the tomatoes and beans. Bring to a simmer, cover, and cook on low, stirring now and then.',20),
   S('Cook the rice','While the chilli simmers, rinse the rice and cook it covered in twice its volume of water. Rest for 5 minutes.',15),
   S('Season and serve','Season with salt and serve the chilli over the rice.'),
   LEFTOVERS]),
 ('d03','dinner','Chicken thigh tray bake',40,True,['Sheet pan'],
  [('chicken_thigh',230),('potato',300),('red_pepper',120),('onion',80),('olive_oil',15),('paprika',2),('oregano',1),('garlic',6),('salt',1)],
  [S('Heat the oven','Heat the oven to 425°F (220°C).'),
   S('Prep the tray','Cut the potatoes into chunks and the pepper and onion into wedges. Toss with the oil, paprika, oregano, garlic and salt on a sheet pan.',5),
   S('Add the chicken','Nestle the seasoned chicken thighs among the vegetables.'),
   S('Roast','Roast until the potatoes are golden and the chicken reaches 165°F (74°C).',35),
   LEFTOVERS]),
 ('d04','dinner','Turkey bolognese',35,True,[],
  [('ground_turkey',200),('spaghetti',100),('canned_tomatoes',200),('mushrooms',80),('onion',50),('olive_oil',8),('garlic',6),('oregano',1),('salt',1)],
  [S('Soften the onion','Heat the oil in a large pan. Cook the diced onion and mushrooms until soft and browned.',6),
   S('Brown the turkey','Add the turkey and cook, breaking it up, until no pink remains (165°F / 74°C).',7),
   S('Simmer the sauce','Add the garlic, oregano, tomatoes and salt. Simmer until thick.',15),
   S('Cook the pasta','Meanwhile boil the spaghetti in salted water until al dente. Drain.',10),
   S('Serve','Toss the pasta with the sauce.'),
   LEFTOVERS]),
 ('d05','dinner','Chickpea and spinach curry',30,True,[],
  [('chickpeas',200),('spinach',100),('coconut_milk',100),('white_rice',85),('onion',60),('garlic',6),('ginger',4),('curry_powder',4),('canned_tomatoes',100),('salt',1)],
  [S('Cook the rice','Rinse the rice and simmer, covered, in twice its volume of water until tender.',18),
   S('Build the base','In a large pan, cook the diced onion in a splash of water until soft. Add the garlic, ginger and curry powder for 1 minute.',6),
   S('Simmer','Add the chickpeas, tomatoes and coconut milk. Simmer until slightly thickened.',12),
   S('Wilt the spinach','Stir in the spinach until it wilts. Season with salt.',2),
   S('Serve','Serve over the rice.'),
   LEFTOVERS]),
 ('d06','dinner','Steak, potatoes and green beans',30,False,[],
  [('sirloin',220),('potato',300),('green_beans',150),('butter',15),('olive_oil',8),('garlic',3),('salt',1),('pepper',0.5)],
  [S('Boil the potatoes','Cut the potatoes into chunks and boil in salted water until tender. Drain.',15),
   S('Cook the steak','Pat the steak dry and season. Sear in the oil in a very hot pan, 3–4 minutes a side for medium. Rest for 5 minutes.',8),
   S('Cook the beans','Steam or boil the green beans until bright and just tender.',4),
   S('Finish','Toss the potatoes and beans with the butter and garlic. Slice the steak and serve.')]),
 ('d07','dinner','Cod with lemon orzo',25,False,[],
  [('cod',230),('pasta',90),('lemon',20),('parmesan',20),('olive_oil',15),('spinach',60),('garlic',3),('salt',1)],
  [S('Cook the orzo','Boil the orzo in salted water until tender. Drain.',10),
   S('Cook the cod','Season the cod. Cook in half the oil in a pan over medium-high heat until it flakes easily (145°F / 63°C).',8),
   S('Finish the orzo','Toss the orzo with the rest of the oil, the garlic, spinach, lemon juice and Parmesan until the spinach wilts.',2),
   S('Serve','Serve the cod on the orzo.')]),
 ('d08','dinner','Black bean tacos',20,False,[],
  [('black_beans',250),('flour_tortilla',110),('cheddar',40),('salsa',80),('avocado',50),('cumin',1),('chili_powder',1),('salt',0.5)],
  [S('Season the beans','Warm the beans in a pan with the cumin, chilli powder, salt and a splash of water, mashing a few.',6),
   S('Warm the tortillas','Warm the tortillas in a dry pan.',2),
   S('Fill','Fill with the beans, cheese, salsa and sliced avocado.')]),
 ('d09','dinner','Teriyaki tofu and broccoli rice',25,False,[],
  [('tofu',220),('broccoli',150),('white_rice',85),('teriyaki',40),('sesame_seeds',8),('olive_oil',10)],
  [S('Cook the rice','Rinse the rice and simmer, covered, in twice its volume of water until tender.',18),
   S('Crisp the tofu','Press the tofu dry and cut into cubes. Fry in the oil over medium-high heat until golden on all sides.',8),
   S('Cook the broccoli','Add the broccoli and a splash of water, cover, and steam until just tender.',3),
   S('Glaze','Pour in the teriyaki sauce and toss until sticky. Serve over the rice with sesame seeds.',1)]),
 ('d10','dinner','Pork tenderloin, rice and slaw',35,False,[],
  [('pork',250),('white_rice',85),('cabbage',120),('carrot',60),('olive_oil',15),('vinegar',15),('paprika',2),('salt',1)],
  [S('Cook the rice','Rinse the rice and simmer, covered, in twice its volume of water until tender.',18),
   S('Sear the pork','Heat the oven to 400°F (200°C). Rub the pork with half the oil, the paprika and salt, and sear it all over in an oven-safe pan.',5),
   S('Roast','Roast until it reaches 145°F (63°C), then rest for 3 minutes before slicing.',15),
   S('Make the slaw','Toss the cabbage and grated carrot with the vinegar and the rest of the oil.'),
   S('Serve','Serve the sliced pork with the rice and slaw.')]),
 ('d11','dinner','Mushroom and barley risotto',45,False,[],
  [('mushrooms',200),('barley',95),('parmesan',30),('onion',60),('olive_oil',15),('veg_broth',400),('butter',10),('garlic',3),('salt',0.5)],
  [S('Brown the mushrooms','Heat the oil in a pot. Cook the mushrooms until browned, then set half aside.',6),
   S('Toast the barley','Add the onion and garlic and cook until soft, then stir in the barley.',4),
   S('Simmer','Add the broth a ladle at a time, stirring often, until the barley is tender and creamy.',35),
   S('Finish','Stir in the butter, Parmesan and reserved mushrooms. Season to taste.')]),
 ('d12','dinner','Chicken fajitas',25,True,[],
  [('chicken_breast',260),('red_pepper',150),('onion',80),('flour_tortilla',100),('sour_cream',40),('olive_oil',10),('chili_powder',2),('cumin',1),('paprika',1),('salt',1),('lemon',5)],
  [S('Season the chicken','Slice the chicken into strips and toss with the chilli powder, cumin, paprika and salt.'),
   S('Cook the chicken','Heat the oil in a large pan over high heat. Cook the chicken until browned and cooked through (165°F / 74°C). Set aside.',7),
   S('Cook the vegetables','Add the sliced pepper and onion and cook until charred at the edges.',6),
   S('Combine','Return the chicken, squeeze over the lemon and toss.'),
   S('Serve','Serve in warm tortillas with sour cream.'),
   LEFTOVERS]),

 ('s01','snacks','Apple and peanut butter',3,False,[],
  [('apple',180),('peanut_butter',32)],
  [S('Slice and serve','Core and slice the apple. Serve with the peanut butter for dipping.')]),
 ('s02','snacks','Protein shake with banana',3,False,['Blender'],
  [('whey',30),('milk',240),('banana',100)],
  [S('Blend','Blend the milk, protein powder and banana until smooth.')]),
 ('s03','snacks','Hummus and pitta',3,False,[],
  [('hummus',60),('pita',60),('cucumber',60)],
  [S('Serve','Warm the pita and cut into wedges. Serve with the hummus and cucumber sticks.')]),
 ('s04','snacks','Trail mix',1,False,[],
  [('almonds',25),('peanuts',20),('raisins',20)],
  [S('Mix','Mix the almonds, peanuts and raisins.')]),
 ('s05','snacks','Boiled eggs and fruit',12,False,[],
  [('boiled_egg',100),('grapes',150),('salt',0.3)],
  [S('Boil the eggs','Lower the eggs into boiling water and cook for 9–10 minutes for firm yolks.',10),
   S('Cool','Cool in cold water, then peel. Season with a pinch of salt and serve with the grapes.',2)]),
 ('s06','snacks','Edamame with sea salt',5,False,[],
  [('edamame',180),('salt',0.5)],
  [S('Cook','Cook the edamame in boiling water until hot.',4),
   S('Season','Drain and toss with the salt.')]),
 ('s07','snacks','Rice cakes with cottage cheese',3,False,[],
  [('rice_cakes',27),('cottage_cheese',150),('pepper',0.2)],
  [S('Top and serve','Spread the cottage cheese over the rice cakes and add a grind of pepper.')]),
 ('s08','snacks','Beef jerky and an orange',1,False,[],
  [('beef_jerky',40),('orange',140)],
  [S('Serve','Peel the orange and serve with the jerky.')]),
]

def total(ings):
    t = {'kcal': 0, 'protein': 0, 'fat': 0, 'carb': 0}
    for k, g in ings:
        n = nut[str(I[k][0])]
        for f in t: t[f] += n.get(f, 0) * g / 100
    return t

if __name__ == '__main__':
    for rid, slot, name, mn, b, eq, ings, steps in R:
        t = total(ings)
        chk = 4*t['protein'] + 4*t['carb'] + 9*t['fat']
        print(f"{rid} {name[:36]:36} {t['kcal']:5.0f} P{t['protein']:4.0f} C{t['carb']:4.0f} F{t['fat']:4.0f} (4/4/9={chk:4.0f}) steps={len(steps)}")

# Planner metadata (Recipe Schema and Planner Rules §2): meal types it fits, how long it keeps, how it
# reheats, main protein, and dish format — the inputs to the variety and leftover rules.
#   id: (mealTypes, leftoverDays, reheat, proteinSource, format)
META = {
 'b01': (['breakfast'], 0, 'cold', 'dairy', 'bowl'),
 'b02': (['breakfast'], 0, 'poor', 'beef', 'hash'),
 'b03': (['breakfast'], 2, 'cold', 'legume', 'oats'),
 'b04': (['breakfast'], 0, 'poor', 'fish', 'toast'),
 'b05': (['breakfast'], 1, 'ok', 'tofu', 'scramble'),
 'b06': (['breakfast'], 1, 'ok', 'egg', 'pancakes'),
 'b07': (['breakfast'], 2, 'ok', 'turkey', 'wrap'),
 'b08': (['breakfast'], 0, 'poor', 'egg', 'skillet'),
 'b09': (['breakfast'], 0, 'poor', 'dairy', 'toast'),
 'b10': (['breakfast', 'snacks'], 3, 'cold', 'mixed', 'pudding'),
 'l01': (['lunch', 'dinner'], 2, 'great', 'chicken', 'bowl'),
 'l02': (['lunch'], 1, 'cold', 'fish', 'salad'),
 'l03': (['lunch'], 0, 'cold', 'turkey', 'wrap'),
 'l04': (['lunch', 'dinner'], 4, 'great', 'legume', 'soup'),
 'l05': (['lunch', 'dinner'], 3, 'cold', 'legume', 'bowl'),
 'l06': (['lunch'], 1, 'cold', 'dairy', 'salad'),
 'l07': (['lunch', 'dinner'], 1, 'ok', 'shellfish', 'stir-fry'),
 'l08': (['lunch', 'dinner'], 3, 'great', 'beef', 'bowl'),
 'l09': (['lunch', 'dinner'], 2, 'great', 'egg', 'stir-fry'),
 'l10': (['lunch'], 0, 'poor', 'chicken', 'wrap'),
 'd01': (['dinner'], 1, 'ok', 'fish', 'plate'),
 'd02': (['dinner'], 3, 'great', 'beef', 'stew'),
 'd03': (['dinner'], 3, 'ok', 'chicken', 'tray bake'),
 'd04': (['dinner'], 3, 'great', 'turkey', 'pasta'),
 'd05': (['dinner', 'lunch'], 4, 'great', 'legume', 'curry'),
 'd06': (['dinner'], 0, 'poor', 'beef', 'plate'),
 'd07': (['dinner'], 1, 'ok', 'fish', 'pasta'),
 'd08': (['dinner'], 0, 'poor', 'legume', 'tacos'),
 'd09': (['dinner', 'lunch'], 2, 'ok', 'tofu', 'stir-fry'),
 'd10': (['dinner'], 2, 'ok', 'pork', 'plate'),
 'd11': (['dinner'], 2, 'ok', 'mixed', 'risotto'),
 'd12': (['dinner'], 2, 'ok', 'chicken', 'wrap'),
 's01': (['snacks'], 0, 'cold', 'legume', 'snack'),
 's02': (['snacks'], 0, 'cold', 'dairy', 'shake'),
 's03': (['snacks'], 0, 'cold', 'legume', 'snack'),
 's04': (['snacks'], 30, 'cold', 'mixed', 'snack'),
 's05': (['snacks'], 4, 'cold', 'egg', 'snack'),
 's06': (['snacks'], 2, 'cold', 'tofu', 'snack'),
 's07': (['snacks'], 0, 'cold', 'dairy', 'snack'),
 's08': (['snacks'], 30, 'cold', 'beef', 'snack'),
}
assert set(META) == {r[0] for r in R}
