/**
 * GENERATED by src/domain/rank-artwork/gen-rank-registry.mjs — DO NOT EDIT BY HAND.
 * Static `assetPath → require()` map for the imported rank badges (Metro needs static
 * literals). Keys are the exact paths `resolveRankArtwork` emits. Regenerate after
 * adding rank art. 32 entries.
 */

export const RANK_ARTWORK_SOURCES: Record<string, number> = {
  'assets/artwork/ranks/architect-1.png': require('@/assets/artwork/ranks/architect-1.png'),
  'assets/artwork/ranks/architect-2.png': require('@/assets/artwork/ranks/architect-2.png'),
  'assets/artwork/ranks/architect-3.png': require('@/assets/artwork/ranks/architect-3.png'),
  'assets/artwork/ranks/architect-4.png': require('@/assets/artwork/ranks/architect-4.png'),
  'assets/artwork/ranks/builder-1.png': require('@/assets/artwork/ranks/builder-1.png'),
  'assets/artwork/ranks/builder-2.png': require('@/assets/artwork/ranks/builder-2.png'),
  'assets/artwork/ranks/builder-3.png': require('@/assets/artwork/ranks/builder-3.png'),
  'assets/artwork/ranks/builder-4.png': require('@/assets/artwork/ranks/builder-4.png'),
  'assets/artwork/ranks/craftsman-1.png': require('@/assets/artwork/ranks/craftsman-1.png'),
  'assets/artwork/ranks/craftsman-2.png': require('@/assets/artwork/ranks/craftsman-2.png'),
  'assets/artwork/ranks/craftsman-3.png': require('@/assets/artwork/ranks/craftsman-3.png'),
  'assets/artwork/ranks/craftsman-4.png': require('@/assets/artwork/ranks/craftsman-4.png'),
  'assets/artwork/ranks/established-f-1.png': require('@/assets/artwork/ranks/established-f-1.png'),
  'assets/artwork/ranks/established-f-2.png': require('@/assets/artwork/ranks/established-f-2.png'),
  'assets/artwork/ranks/established-f-3.png': require('@/assets/artwork/ranks/established-f-3.png'),
  'assets/artwork/ranks/established-f-4.png': require('@/assets/artwork/ranks/established-f-4.png'),
  'assets/artwork/ranks/established-m-1.png': require('@/assets/artwork/ranks/established-m-1.png'),
  'assets/artwork/ranks/established-m-2.png': require('@/assets/artwork/ranks/established-m-2.png'),
  'assets/artwork/ranks/established-m-3.png': require('@/assets/artwork/ranks/established-m-3.png'),
  'assets/artwork/ranks/established-m-4.png': require('@/assets/artwork/ranks/established-m-4.png'),
  'assets/artwork/ranks/foundation-1.png': require('@/assets/artwork/ranks/foundation-1.png'),
  'assets/artwork/ranks/foundation-2.png': require('@/assets/artwork/ranks/foundation-2.png'),
  'assets/artwork/ranks/foundation-3.png': require('@/assets/artwork/ranks/foundation-3.png'),
  'assets/artwork/ranks/foundation-4.png': require('@/assets/artwork/ranks/foundation-4.png'),
  'assets/artwork/ranks/legacy-1.png': require('@/assets/artwork/ranks/legacy-1.png'),
  'assets/artwork/ranks/legacy-2.png': require('@/assets/artwork/ranks/legacy-2.png'),
  'assets/artwork/ranks/legacy-3.png': require('@/assets/artwork/ranks/legacy-3.png'),
  'assets/artwork/ranks/legacy-4.png': require('@/assets/artwork/ranks/legacy-4.png'),
  'assets/artwork/ranks/legend-1.png': require('@/assets/artwork/ranks/legend-1.png'),
  'assets/artwork/ranks/legend-2.png': require('@/assets/artwork/ranks/legend-2.png'),
  'assets/artwork/ranks/legend-3.png': require('@/assets/artwork/ranks/legend-3.png'),
  'assets/artwork/ranks/legend-4.png': require('@/assets/artwork/ranks/legend-4.png'),
};
