/**
 * Screen background artwork — the design's per-screen photographic/textured backgrounds, imported
 * from the handoff. These EXISTED in `design_reference/.../assets/` and were simply never wired
 * (FORGE_DELTAS §16 — a DROPPED-FREE miss, the app rendered a flat gradient instead). Metro needs
 * static `require()` literals. Consumed only via `<ScreenBackground image={SCREEN_BG.x} />`.
 *
 * Palette (from the `.dc` set): `slate` = default standard screens; `slate2` = settings / program /
 * records; `bg2` = create / detail screens; `legacy` = Legacy-family (mountains, the `legacyMountains`
 * layer drives the scroll-fade); `squadDetail` / `squadsHub` = the two squad surfaces.
 *
 * ══ BOTH PALETTES ARE ENUMERATED, AND THAT IS NOT AVOIDABLE ══
 *
 * Metro resolves `require()` from a STRING LITERAL at build time — it cannot take a variable, so the
 * theme cannot be interpolated into the path. Both sets are written out and the choice is made here,
 * once, on the resolved module. The 205 `<ScreenBackground>` call sites are untouched: they ask for
 * `SCREEN_BG.slate` and get whichever plate the active theme means by that.
 *
 * ⚠ THIS DOUBLES THE PLATES IN THE BUNDLE — `assets/backgrounds/` goes from 24 MB to 45 MB, and both
 *   sets ship to every athlete regardless of which theme they use. That is the price of a build-time
 *   `require` and it is worth stating plainly rather than discovering in a bundle report. If it needs
 *   to come down, the lever is downscaling the plates (they are 853×1844 for a 404pt-wide screen), not
 *   dropping a theme.
 *
 * The Paper plates are generated by `scripts/paper-plates/recolor.py` — a reproducible transform, not
 * hand-exported binaries. See that file for the mapping and for why `hero-mountains` takes the
 * opposite one.
 */

import { IS_PAPER } from './foundation.ts';

const FORGE_BG = {
  slate: require('@/assets/backgrounds/forge-slate.png'),
  slate2: require('@/assets/backgrounds/forge-slate2.png'),
  bg2: require('@/assets/backgrounds/forge-bg-2.png'),
  legacy: require('@/assets/backgrounds/legacy-bg.png'),
  legacyMountains: require('@/assets/backgrounds/hero-mountains.png'),
  squadDetail: require('@/assets/backgrounds/squad-bg-continued.png'),
  squadsHub: require('@/assets/backgrounds/squads-hub-bg.png'),
} as const;

const PAPER_BG = {
  slate: require('@/assets/backgrounds/forge-slate-paper.png'),
  slate2: require('@/assets/backgrounds/forge-slate2-paper.png'),
  bg2: require('@/assets/backgrounds/forge-bg-2-paper.png'),
  legacy: require('@/assets/backgrounds/legacy-bg-paper.png'),
  legacyMountains: require('@/assets/backgrounds/hero-mountains-paper.png'),
  squadDetail: require('@/assets/backgrounds/squad-bg-continued-paper.png'),
  squadsHub: require('@/assets/backgrounds/squads-hub-bg-paper.png'),
} as const;

export const SCREEN_BG = IS_PAPER ? PAPER_BG : FORGE_BG;

/**
 * Screen-level bronze radial-glows, verbatim from each `.dc`'s `radial-gradient(rx ry at cx cy,
 * color 0%, transparent stop)` (FORGE_DELTAS §16). Peaks sit off-screen so only the falloff frames the
 * top/bottom edge. Consumed via `<ScreenBackground radials={[BG_RADIAL.x]} />`.
 *
 * ⚠ THE PAPER ALPHAS ARE HIGHER, NOT LOWER, and that is the opposite of the instinct. A 5% bronze wash
 *   is visible against near-black and invisible against cream — there is simply less room between
 *   `#F4F0E6` and a warm bronze than between `#050505` and one. The hues are the same; only the
 *   strength moves, so the framing these give the screen survives the theme.
 */
const FORGE_RADIAL = {
  /** Friends Feed apex — `120% 44% at 50% -4%`, bronze. */
  friendsApex: { cx: '50%', cy: '-4%', rx: '120%', ry: '44%', color: 'rgba(186, 134, 84,0.05)', stop: 0.6 },
  /** Squad Detail top — `100% 40% at 50% -6%`, bronze. */
  squadTop: { cx: '50%', cy: '-6%', rx: '100%', ry: '40%', color: 'rgba(186, 134, 84,0.05)', stop: 0.6 },
  /** Squad Detail bottom — `120% 62% at 50% 108%`, warm. */
  squadBottom: { cx: '50%', cy: '108%', rx: '120%', ry: '62%', color: 'rgba(150,110,60,0.06)', stop: 0.6 },
} as const;

const PAPER_RADIAL = {
  friendsApex: { cx: '50%', cy: '-4%', rx: '120%', ry: '44%', color: 'rgba(164,122,61,0.10)', stop: 0.6 },
  squadTop: { cx: '50%', cy: '-6%', rx: '100%', ry: '40%', color: 'rgba(164,122,61,0.10)', stop: 0.6 },
  squadBottom: { cx: '50%', cy: '108%', rx: '120%', ry: '62%', color: 'rgba(122,100,66,0.12)', stop: 0.6 },
} as const;

export const BG_RADIAL = IS_PAPER ? PAPER_RADIAL : FORGE_RADIAL;
